/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { IQueryClientProvider, ISigningClientProvider, IMessageComposerProvider } from "./contractContextBase";
import { Cw721QueryClient } from "./Cw721.client";
import { Cw721Client } from "./Cw721.client";
import { Cw721MessageComposer } from "./Cw721.message-composer";
import { Cw721 } from "./Cw721.provider";
export interface IContractsContext {
  cw721: IQueryClientProvider<Cw721QueryClient> & ISigningClientProvider<Cw721Client> & IMessageComposerProvider<Cw721MessageComposer>;
}
export const getProviders = (address?: string, cosmWasmClient?: CosmWasmClient, signingCosmWasmClient?: SigningCosmWasmClient) => ({
  cw721: new Cw721({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  })
});