/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { Cw721Client, Cw721QueryClient } from "./Cw721.client";
import { Cw721MessageComposer } from "./Cw721.message-composer";
export class Cw721 extends ContractBase<Cw721Client, Cw721QueryClient, Cw721MessageComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, Cw721Client, Cw721QueryClient, Cw721MessageComposer);
  }

}