/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw721.types";
import * as _1 from "./Cw721.client";
import * as _2 from "./Cw721.message-composer";
import * as _3 from "./Cw721.provider";
export namespace contracts {
  export const Cw721 = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}